name: Node.js

on: push

jobs:
  without_build_cloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:nodejs"

  with_build_cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "tadashinemoto567/demo"
          install: true
      - uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:nodejs"
          outputs: 'type=cacheonly'
